# Generated by Django 3.2.4 on 2021-06-12 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingmessage',
            name='body',
            field=models.CharField(blank=True, choices=[('Professional Makeup', 'Professional Makeup'), ('Manicure Pedicure', 'Manicure Pedicure'), ('Body Treatment', 'Body Treatment'), ('Haircut&Colouring', 'Haircut&Colouring')], default='Professional Makeup', max_length=200, null=True),
        ),
    ]
