# Generated by Django 3.2.4 on 2021-06-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0005_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='time',
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
