# Generated by Django 3.2.4 on 2021-06-24 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0007_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='name',
        ),
    ]
