# Generated by Django 3.2.4 on 2021-06-24 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0008_remove_post_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='form_image',
        ),
    ]
