# Generated by Django 3.2.4 on 2021-06-27 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0009_rename_image_post_form_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post',
            field=models.TextField(blank=True, null=True),
        ),
    ]
