# Generated by Django 3.2.4 on 2021-07-04 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0010_alter_post_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='blogs_img2',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='blogs_img3',
        ),
    ]
