# Generated by Django 3.2.5 on 2021-07-06 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0011_auto_20210704_0715'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='gallery_img10',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='setting',
            name='gallery_img11',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='setting',
            name='gallery_img12',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='setting',
            name='gallery_img13',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='setting',
            name='gallery_img14',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='setting',
            name='gallery_img15',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='setting',
            name='gallery_img16',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='setting',
            name='gallery_img9',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
